'use client';

import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import BackButton from '@/components/ui/BackButton';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center gap-3">
          <BackButton />
          <h1 className="font-bold text-gray-900">Privacy Policy</h1>
        </div>
      </header>

      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-2xl shadow p-6 md:p-8 prose prose-sm max-w-none">
          <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-gray-500 text-sm mb-6">Last updated: July 05, 2026</p>

          <p className="mb-4">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>

          <p className="mb-4">
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">Interpretation</h3>
          <p className="mb-4">The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Definitions</h3>
          <p className="mb-4">For the purposes of this Privacy Policy:</p>

          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to <strong>YouTask</strong>.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: <strong>Pakistan</strong>.</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to YouTask, accessible from <a href="https://audio-rewards-platform.vercel.app" className="text-purple-600 hover:underline">https://audio-rewards-platform.vercel.app</a>.</li>
            <li><strong>You</strong> means the individual accessing or using the Service.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">Types of Data Collected</h3>

          <h4 className="text-lg font-semibold mt-4 mb-2">Personal Data</h4>
          <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Username</li>
          </ul>

          <h4 className="text-lg font-semibold mt-4 mb-2">Usage Data</h4>
          <p className="mb-4">Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

          <h4 className="text-lg font-semibold mt-4 mb-2">Tracking Technologies and Cookies</h4>
          <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>

          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
            <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.</li>
          </ul>

          <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>

          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Necessary / Essential Cookies</strong> - These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</li>
            <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> - These Cookies identify if users have accepted the use of cookies on the Website.</li>
            <li><strong>Functionality Cookies</strong> - These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">Use of Your Personal Data</h3>
          <p className="mb-4">The Company may use Personal Data for the following purposes:</p>

          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers, and general information about other goods, services and events which We offer.</li>
            <li>To manage Your requests: To attend and manage Your requests to Us.</li>
            <li>For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
            <li>To process user earnings and payouts: We use your registered user information, email, and provided phone numbers/wallet details strictly to verify completed audio tasks and safely process your withdrawal requests.</li>
          </ul>

          <p className="mb-4">We may share Your Personal Data in the following situations:</p>

          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>With Service Providers: We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li>For business transfers: We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
            <li>With Affiliates: We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
            <li>With business partners: We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
            <li>With other users: If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
            <li>With Your consent: We may disclose Your Personal Data for any other purpose with Your consent.</li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">Retention of Your Personal Data</h3>
          <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Transfer of Your Personal Data</h3>
          <p className="mb-4">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Delete Your Personal Data</h3>
          <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section that allows you to manage Your personal information.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Disclosure of Your Personal Data</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">Business Transactions</h3>
          <p className="mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Law enforcement</h3>
          <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

          <h3 className="text-xl font-semibold mt-6 mb-3">Other legal requirements</h3>
          <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>

          <ul className="list-disc pl-6 mb-4">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">Security of Your Personal Data</h3>
          <p className="mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Children's Privacy</h2>
          <p className="mb-4">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Advertising and Third-Party Ad Networks</h2>
          <p className="mb-4">We use third-party advertising companies to serve ads when you visit our Website. In particular, we partner with <strong>Adsterra</strong> to display advertisements. These third-party ad servers or ad networks use technologies like cookies, JavaScript, or Web Beacons within their respective advertisements and links that appear on YouTask, which are sent directly to users' browsers.</p>
          <p className="mb-4">They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Please note that YouTask has no access to or control over these cookies that are used by third-party advertisers.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Links to Other Websites</h2>
          <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Changes to this Privacy Policy</h2>
          <p className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p className="mb-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
          <p className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
          <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc pl-6">
            <li>By email: <a href="mailto:awaisealtaf@gmail.com" className="text-purple-600 hover:underline">awaisealtaf@gmail.com</a></li>
          </ul>
        </div>
      </div>
    </div>
  );
}